var DB1 = {
    "spirits" :
        [{
            "nr": "10001",
            "articleid": "25053",
            "articletype": "100",
            "name": "Braastad XO",
            "name2": "",
            "priceinclvat": "442.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2000-08-07",
            "finaldelivery": " ",
            "catgegory": "Cognac",
            "packaging": "Flaska",
            "captype": "Naturkork",
            "countryoforigin": "Cognac, Fine Champagne",
            "countryoforiginlandname": "Frankrike",
            "producer": "Tiffon",
            "provider": "Arcus Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "40%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1001",
            "articleid": "190719",
            "articletype": "10",
            "name": "Vanlig Vodka",
            "name2": "",
            "priceinclvat": "195.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2006-04-01",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Svensk Export Vodka AB",
            "provider": "Fondberg",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1001201",
            "articleid": "51029",
            "articletype": "10012",
            "name": "Dworek Vodka",
            "name2": "",
            "priceinclvat": "190.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2004-12-06",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Polen",
            "producer": "Tarpan Fabryka Likierow",
            "provider": "TIWA Trading AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1001202",
            "articleid": "407506",
            "articletype": "10012",
            "name": "Dworek Vodka",
            "name2": "",
            "priceinclvat": "100.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2009-10-01",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "",
            "countryoforiginlandname": "Polen",
            "producer": "Tarpan Fabryka Likierow",
            "provider": "TIWA Trading AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1003802",
            "articleid": "513291",
            "articletype": "10038",
            "name": "Esping Jul B\u00c3\u00a4sk",
            "name2": "",
            "priceinclvat": "195.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2010-11-15",
            "finaldelivery": " ",
            "catgegory": "Kryddad sprit",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Symposion International",
            "provider": "Symposion International AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "32%",
            "module": "",
            "assortment": "TSS",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1004703",
            "articleid": "723841",
            "articletype": "10047",
            "name": "Nils Oscar",
            "name2": "Celebration Ale",
            "priceinclvat": "43.70",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-02-01",
            "finaldelivery": " ",
            "catgegory": "\u00c3\u2013l, Ale",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Nils Oscar Company",
            "provider": "The Nils Oscar Company AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "9.4%",
            "module": "T5",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1004801",
            "articleid": "733051",
            "articletype": "10048",
            "name": "Rhum J. M",
            "name2": "",
            "priceinclvat": "729.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Rom, M\u00c3\u00b6rk",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Martinique",
            "countryoforiginlandname": "Frankrike",
            "producer": "Les Heritiers Crassous de Mede",
            "provider": "Cask Sweden AB",
            "productionyear": "2001",
            "testedproductionyear": "",
            "alcoholstrength": "46.6%",
            "module": "T7",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1004901",
            "articleid": "733068",
            "articletype": "10049",
            "name": "Rhum J.M",
            "name2": "",
            "priceinclvat": "1399.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-04-02",
            "finaldelivery": " ",
            "catgegory": "Rom, M\u00c3\u00b6rk",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Martinique",
            "countryoforiginlandname": "Frankrike",
            "producer": "Les Heritiers Crassous de Mede",
            "provider": "Cask Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "44.8%",
            "module": "T7",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1005001",
            "articleid": "733084",
            "articletype": "10050",
            "name": "Balcones Texas",
            "name2": "",
            "priceinclvat": "899.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Whisky, Malt",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "USA",
            "producer": "Balcones Distilling",
            "provider": "Cask Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "52.2%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1005101",
            "articleid": "733200",
            "articletype": "10051",
            "name": "Balcones Brimstone",
            "name2": "",
            "priceinclvat": "899.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Whisky, \u00c3\u2013vrig",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "USA",
            "producer": "Balcones Distilling",
            "provider": "Cask Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "53.2%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1005201",
            "articleid": "733236",
            "articletype": "10052",
            "name": "Balcones True Blue",
            "name2": "",
            "priceinclvat": "899.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Whisky, \u00c3\u2013vrig",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "USA",
            "producer": "Balcones Distilling",
            "provider": "Cask Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "50.2%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1005401",
            "articleid": "733429",
            "articletype": "10054",
            "name": "Linkwood",
            "name2": "the Octave",
            "priceinclvat": "1159.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Whisky, Malt",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Skottland, Highlands, Speyside",
            "countryoforiginlandname": "Storbritannien",
            "producer": "Duncan Taylor Scotch Whisky",
            "provider": "Clydesdale AB",
            "productionyear": "1989",
            "testedproductionyear": "",
            "alcoholstrength": "51.7%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1005502",
            "articleid": "733446",
            "articletype": "10055",
            "name": "Marolo",
            "name2": "Grappa di Arneis Vigneto Renesio",
            "priceinclvat": "481.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-03-01",
            "finaldelivery": " ",
            "catgegory": "Grappa och Marc, Grappa",
            "packaging": "Flaska",
            "captype": "Naturkork",
            "countryoforigin": "",
            "countryoforiginlandname": "Italien",
            "producer": "Distilleria St Teresa dei Frat",
            "provider": "Haugen-Gruppen AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "50%",
            "module": "T7",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1005602",
            "articleid": "733468",
            "articletype": "10056",
            "name": "Cl\u00c3\u00a9ment",
            "name2": "Single Cask",
            "priceinclvat": "529.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-04-02",
            "finaldelivery": " ",
            "catgegory": "Rom, M\u00c3\u00b6rk",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Martinique",
            "countryoforiginlandname": "Frankrike",
            "producer": "Les Heritiers Crassous de Mede",
            "provider": "Cask Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "47.6%",
            "module": "T7",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "101",
            "articleid": "1",
            "articletype": "1",
            "name": "Renat",
            "name2": "",
            "priceinclvat": "203.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "1993-10-01",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Internationellt m\u00c3\u00a4rke",
            "producer": "Pernod Ricard",
            "provider": "Pernod Ricard Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "37.5%",
            "module": "",
            "assortment": "FS",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1010001",
            "articleid": "817007",
            "articletype": "10100",
            "name": "Romano Levi",
            "name2": "Mostaco d\u00c2\u00b4Asti Donna Selvatica",
            "priceinclvat": "790.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2014-04-01",
            "finaldelivery": " ",
            "catgegory": "Grappa och Marc, Grappa",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Italien",
            "producer": "Distilleria Levi Serafino ( di",
            "provider": "Haugen-Gruppen AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "40%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1010404",
            "articleid": "611864",
            "articletype": "10104",
            "name": "Giare 5 Grappe",
            "name2": "Moscato, Amarone, Teroldego, Chardonnay, Prosecco",
            "priceinclvat": "399.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-03-01",
            "finaldelivery": " ",
            "catgegory": "Grappa och Marc, Grappa",
            "packaging": "5 flaskor \u00c3\u00a0 100 ml",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Italien",
            "producer": "Marzadro",
            "provider": "Stragas-Gruppen AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "40%",
            "module": "",
            "assortment": "TST",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1010501",
            "articleid": "659534",
            "articletype": "10105",
            "name": "Genuin 25",
            "name2": "",
            "priceinclvat": "149.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-09-01",
            "finaldelivery": " ",
            "catgegory": "Okryddad sprit",
            "packaging": "Flaska",
            "captype": "Skruvkapsyl",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Svensk Vodka i Motala AB",
            "provider": "Svensk Vodka i Motala AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "25%",
            "module": "",
            "assortment": "TST",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1011302",
            "articleid": "723428",
            "articletype": "10113",
            "name": "Kullados",
            "name2": "",
            "priceinclvat": "499.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-04-02",
            "finaldelivery": " ",
            "catgegory": "\u00c3\u2013vrig sprit",
            "packaging": "Flaska",
            "captype": "Plastkork\/syntetkork",
            "countryoforigin": "",
            "countryoforiginlandname": "Sverige",
            "producer": "Kullabygdens Musteri AB",
            "provider": "Kullabygdens Destilleri AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "40%",
            "module": "T5",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1011401",
            "articleid": "811782",
            "articletype": "10114",
            "name": "Grappa Riserva Levi Romano",
            "name2": "Distilleria Levi Serafino Donna Selvatica",
            "priceinclvat": "989.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2014-03-01",
            "finaldelivery": " ",
            "catgegory": "Grappa och Marc, Grappa",
            "packaging": "Flaska",
            "captype": "Naturkork",
            "countryoforigin": "",
            "countryoforiginlandname": "Italien",
            "producer": "Distilleria Levi Serafino ( di",
            "provider": "Haugen-Gruppen AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "50%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1011601",
            "articleid": "614078",
            "articletype": "10116",
            "name": "Glenmorangie",
            "name2": "Pride",
            "priceinclvat": "24500.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-02-23",
            "finaldelivery": " ",
            "catgegory": "Whisky, Malt",
            "packaging": "Flaska",
            "captype": "Naturkork",
            "countryoforigin": "Skottland, Highlands, Northern Highlands",
            "countryoforiginlandname": "Storbritannien",
            "producer": "Glenmorangie",
            "provider": "Mo\u00c3\u00abt Hennessy Sverige AB",
            "productionyear": "1981",
            "testedproductionyear": "",
            "alcoholstrength": "56.7%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1011701",
            "articleid": "734763",
            "articletype": "10117",
            "name": "The Arran Malt",
            "name2": "Orkney Bere",
            "priceinclvat": "579.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-04-02",
            "finaldelivery": " ",
            "catgegory": "Whisky, Malt",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Skottland, Highlands, Islands, Arran",
            "countryoforiginlandname": "Storbritannien",
            "producer": "Isle of Arran Distillers",
            "provider": "Cask Sweden AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "46%",
            "module": "T7",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1011901",
            "articleid": "614800",
            "articletype": "10119",
            "name": "Glen Garioch",
            "name2": "Mackillop's Choice",
            "priceinclvat": "895.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2012-02-01",
            "finaldelivery": " ",
            "catgegory": "Whisky, Malt",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "Skottland, Highlands",
            "countryoforiginlandname": "Storbritannien",
            "producer": "Angus Dundee",
            "provider": "Philipson S\u00c3\u00b6derberg AB",
            "productionyear": "1990",
            "testedproductionyear": "",
            "alcoholstrength": "43%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1012601",
            "articleid": "874805",
            "articletype": "10126",
            "name": "Nikka Taketsuru",
            "name2": "Pure Malt",
            "priceinclvat": "549.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2014-10-03",
            "finaldelivery": " ",
            "catgegory": "Whisky, Malt",
            "packaging": "Flaska",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Japan",
            "producer": "The Nikka Whisky Distilling Co",
            "provider": "Symposion International AB",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "43%",
            "module": "",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }, {
            "nr": "1013104",
            "articleid": "734572",
            "articletype": "10131",
            "name": "Poli Grappa Barrel Pack",
            "name2": "",
            "priceinclvat": "549.00",
            "volumeml": null,
            "priceperlitre": null,
            "introduced": "2013-04-02",
            "finaldelivery": " ",
            "catgegory": "Grappa och Marc, Grappa",
            "packaging": "5 flaskor \u00c3\u00a0 100 ml",
            "captype": "",
            "countryoforigin": "",
            "countryoforiginlandname": "Italien",
            "producer": "Distillerie Poli",
            "provider": "Bibendum",
            "productionyear": "",
            "testedproductionyear": "",
            "alcoholstrength": "40%",
            "module": "T7",
            "assortment": "TSE",
            "organic": "0",
            "kosher": "0"
        }

        ]
    };